name: builder

on:
  push:
    branches:
      - 'master'
      - 'release-*'

  pull_request:
    branches:
      - 'master'
      - 'release-*'
  
defaults:
  run:
    shell: bash
jobs:

  prepare_ci_run:
    name: Build Website
    # Prepare CI Run looks at what has been changed in this commit/PR/... and determines which artifacts should be
    # built afterwards (in other jobs that depend on this one).
    runs-on: ubuntu-20.04
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # need to checkout "all commits" for certain features to work (e.g., get all changed files)

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Build CodeLabs
        run: |
          go install github.com/googlecodelabs/tools/claat
          for i in $(ls *.md); do claat export $i; done
        working-directory: ./site/codelabs

      - name: Build Site
        run: |
          npm install
          gulp dist 
          rm -f ./dist/codelabs
          cp -r ./codelabs ./dist/ 
        working-directory: ./site

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release-*' }}
        with:
          branch: production # The branch the action should deploy to.
          folder: ./site/dist # The folder the action should deploy.
          target-folder: /
